### ISSUE TITLE
"Apply star sizes to right columns" sizes all right columns to current column size

### ISSUE THREAD

**Issue by sngbrdb** [tom-englert/ProjectConfigurationManager#11]
Visual Studio 2015
PCM version 1.0.10.0

When ctrl-clicking a column header divider to "apply star sizes to right columns", the column clicked is resized to its current data/header.  However, all columns to the right are resized to the same size as the column clicked (expected behaviour would be to resize each of those columns to the size of their respective data or headers).  

Steps to reproduce:
1.  Display columns FileAlignment and ProjectTypeGuids.  Make sure the ProjectTypeGuids column is to the right of the FileAlignment column (also make sure you have at least one project displayed with a project type guid).
2.  Double-click the right side of the ProjectTypeGuids column header to size it according to the data.  The column will be 3-4 times wider than the FileAlignment column.
3.  Hold the ctrl key down and double-click the right side of the FileAlignment column header.  The FileAlignment column will resize, and so will the ProjectTypeGuids column... the ProjectTypeGuids column is now narrower, matching the width of the FileAlignment column.  

Note:  If the FileAlignment column does not resize (because it is already at the correct width), the columns to the right will not resize.  Make the column narrower to trigger the change before testing, if necessary.

**Comment by tom-englert** [comment]
This is a feature of https://github.com/tom-englert/DataGridExtensions, and intended to work like this. 

Since DGX it's used in other projects, too (e.g. https://github.com/tom-englert/ResXResourceManager), it can't be changed easily.

**Comment by sngbrdb** [comment]
Bummer.  Are there advantages to doing the resizing this way?  I can go through and click each column individually, not a big deal... the problem is that if I expand or reduce the window size, I have to go back and reset them all again - resizing the width shrinks all the columns (rather than keeping them the same size and letting the user use the scroll bar at the bottom).  Also, the resizing is inconsistent... if I shrink the width, the columns all shrink, but if I expand it again to the original size, the columns don't get wider again - they stay at the shrinked size.

For a tool like this, though, I can live with any level of interface quirks  :grinning:

**Comment by tom-englert** [comment]
Strange, I can't reproduce this, either. When I resize the columns beyond window size with shift or ctrl, the size stays when the window resizes - unless the windows size gets beyond column sizes.

What windows version are you using?

**Comment by tom-englert** [comment]
I think I got what you are trying to do - when you resize all columns, and the window is wider than all columns, resizing the window will expand the columns again. This is intended - only if the columns are wider than the window, a scroll bar is shown and the size of the columns stays.
