### ISSUE TITLE
Project Configuration Manager doesn't display settings for unloaded projects

### ISSUE THREAD

**Issue by sngbrdb** [tom-englert/ProjectConfigurationManager#12]
Visual Studio 2015
PCM version 1.0.10.0

When unloading a project to speed up multiple changes, PCM doesn't display the project settings in the project list.  

Desired behaviour:  Project would be displayed and saved (but not reloaded) on changes.

Steps to reproduce:
1.  Right click on a project in the solution explorer and pick "unload"
2.  Open Project Configuration Manager.  All projects are listed except for the unloaded project.

**#nicetohave**

**Comment by tom-englert** [comment]
Would be nice, but hard to realize, because some information is only available for loaded projects... (including the list of project).
