### ISSUE TITLE
Only Debug and Release configuration shown

### ISSUE THREAD

**Issue by danielwagn3r** [tom-englert/ProjectConfigurationManager#13]
In Visual Studio 2017 RC1 only the solution and project configurations `Debug `and `Release `are shown, although there are others, too. Couldn't find a way to display them.

**Comment by tom-englert** [comment]
Sorry for the late reply. I could not reproduce this with the latest VS2017, do you still have this issue?

**Comment by danielwagn3r** [comment]
I've checked it last week and there was still the same behaviour, was there a change regarding this?

**Comment by tom-englert** [comment]
No, it always worked:

![image](https://cloud.githubusercontent.com/assets/10229954/25305108/b98a7214-2775-11e7-946c-e44bbb6674db.png)

Maybe you have to reload the solution after adding configurations, sometimes the notifications from VS are missing, so PCM does not refresh automatically.

**Comment by tom-englert** [comment]
@kwaxi do you have a different behavior?

**Comment by tom-englert** [comment]
@kwaxi can you please provide more details - it's not really clear to me what your problem is.

**Comment by danielwagn3r** [comment]
Sorry for the delay. I've a project with five build configurations, but only Debug and Release are shown.

![image](https://cloud.githubusercontent.com/assets/5670510/26281508/6e3571ac-3df9-11e7-9984-eba92f3370e6.png)

![image](https://cloud.githubusercontent.com/assets/5670510/26281515/9688000c-3df9-11e7-9020-a06b344ceeea.png)

**Comment by tom-englert** [comment]
![image](https://cloud.githubusercontent.com/assets/10229954/26646702/e52e2740-463c-11e7-8d60-4d00d9a0a703.png)

They are all there, where is your problem?

**Comment by danielwagn3r** [comment]
Right, but I miss them under _Configuration_

![image](https://cloud.githubusercontent.com/assets/5670510/26664874/65b99a0e-4695-11e7-8070-f59d0e07fe8c.png)

**Comment by tom-englert** [comment]
These are the project configurations - they are independent of the solution configurations.
This table is to map what project configuration is built with each solution configuration.
If you want to have individual project configurations for every solution configuration, you have to create them per project.
However I would not recommend doing so, even with PCM you will end up in the maintenance hell.
