### ISSUE TITLE
How to filter out unwanted projects?

### ISSUE THREAD

**Issue by IneedHelp** [tom-englert/ProjectConfigurationManager#19]
Hello, and thank you for this wonderful extension.

Is there a way to filter out unwanted projects such as unloaded projects or projects that are set not be built?
I'm interested in this because the project properties tab gets crowded with a lot of projects I don't want to see (but I don't want to completely remove them from the solution either).

**Comment by tom-englert** [comment]
You can add some tags in the `Tags` column, then filter by tags.

**Comment by IneedHelp** [comment]
I understand, thank you very much!
