### ISSUE TITLE
Cannot install in Visual Studio Professional 2019.

### ISSUE THREAD

**Issue by jvsca** [tom-englert/ProjectConfigurationManager#23]
When trying to install in Visual Studio Professional 2019 the follow message is shown:
"The extension cannot be installed to this product due to prerequisites that cannot be resolved."

![VSIX Installer Error](https://user-images.githubusercontent.com/2821731/56096817-d4491c80-5eba-11e9-8989-1009d13184b1.png)

Tried the following, but still cannot install:
1- From <Dependencies>:
   Delete:
`    <Dependency Id="Microsoft.VisualStudio.MPF.11.0" DisplayName="Visual Studio MPF 11.0" Version="[11.0,12.0)" />`

   Change:
   From:
`        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.6.2,]" />`
   To:
`        <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="[4.5,)" />`

2- Change in <Prerequisites>:
   From:
`        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0.25824.0,16.0)" DisplayName="Visual Studio core editor" />`
   To:
`
        <Prerequisite Id="Microsoft.VisualStudio.Component.CoreEditor" Version="[15.0,)" DisplayName="Visual Studio core editor" />`
`        <Prerequisite Id="Microsoft.VisualStudio.Component.Roslyn.LanguageServices" Version="[15.0,)" DisplayName="C# and Visual Basic" />`

**Comment by jws305** [comment]
Did you figure out how to get this installed?

**Comment by jvsca** [comment]
Version 1.9.2171 installs properly.
Thanks.
