### ISSUE TITLE
Crashes VS2015 C++ solution repeatedly

### ISSUE THREAD

**Issue by stgagnon** [tom-englert/ProjectConfigurationManager#24]
Usually (always?) in the Properties tab, when checking/unchecking the Show Properities filtering checkboxes.
VC++ solution has 4 projects in it.

Seems to happen mostly when un-checking.

**Comment by tom-englert** [comment]
Hard to say without having a stack dump. Best way would be to debug this on your own...

**Comment by tom-englert** [comment]
VS2015 is now really outdated
