### ISSUE TITLE
Delete option disabled

### ISSUE THREAD

**Issue by corliss** [tom-englert/ProjectConfigurationManager#3]
I was able to delete a single row in the Build Configuration grid. After that the Delete menu item is grayed out for all other items.

Is this a bug?

**Comment by tom-englert** [comment]
You may only delete rows where all configurations are unchecked. If you have a mixed selection, Delete is disabled.

**Comment by corliss** [comment]
Ah, that makes sense, thanks.

**Comment by tom-englert** [comment]
P.S. If you find this project useful, you're invited to "donate" some stars:   https://visualstudiogallery.msdn.microsoft.com/cf7efe17-ae87-40fe-a1e2-f2d61907f043/view/Reviews
