### ISSUE TITLE
Delete multiple rows, and enable the Del key to delete

### ISSUE THREAD

**Issue by corliss** [tom-englert/ProjectConfigurationManager#4]
Thanks for a very useful tool.

Deleting a single row at a time using the Delete menu item is quite frustrating. It would be great if

a) The Del key could be used for deletion, and
b) Multiple rows could be selected (multiple selection is already enabled for the grid) and then deleted together. I don't know if multiple deletion currently works because I ran into #3.

**Comment by tom-englert** [comment]
That should already work - however you may only delete rows where **all** configurations are unchecked. If you have a mixed selection, Delete is disabled. I guess that's what you ran into with #3.

**Comment by corliss** [comment]
OK, great. Thanks.
