### ISSUE TITLE
Empty window and exception in output

### ISSUE THREAD

**Issue by picrap** [tom-englert/ProjectConfigurationManager#6]
Hi,

I'm sorry to say that I have an exception when trying to use this tool.

> System.ArgumentException: URI formats are not supported.
>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
>    at System.IO.Path.GetFullPathInternal(String path)
>    at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
>    at tomenglertde.ProjectConfigurationManager.Model.ProjectFile..ctor(Solution solution, Project project)
>    at tomenglertde.ProjectConfigurationManager.Model.Project..ctor(Solution solution, Project project)
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.<GetProjects>b__38_0(Project project)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.SynchronizeCollections()
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.Update()
> System.ArgumentException: URI formats are not supported.
>    at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
>    at System.IO.Path.GetFullPathInternal(String path)
>    at System.IO.File.InternalGetLastWriteTimeUtc(String path, Boolean checkHost)
>    at tomenglertde.ProjectConfigurationManager.Model.ProjectFile..ctor(Solution solution, Project project)
>    at tomenglertde.ProjectConfigurationManager.Model.Project..ctor(Solution solution, Project project)
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.<GetProjects>b__38_0(Project project)
>    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.SynchronizeCollections()
>    at tomenglertde.ProjectConfigurationManager.Model.Solution.Update()

Let me know if you need some more information or want to make some more tests.

**Comment by tom-englert** [comment]
Looks like the solution has projects which are not located on a local drive. This will be hard to support..

**Comment by picrap** [comment]
It may look like this, but it's not the case: all projects are on a hard drive, and all projects are located below the solution file (just as we would expect from any solution :smile:  )

**Comment by tom-englert** [comment]
So I wonder why the project file path is an URI instead of a file name? What does your solution look like?

**Comment by picrap** [comment]
There is a web site in it, this is the only URI I could find.

**Comment by tom-englert** [comment]
OK, then it can be fixed by skipping web site projects. 
You can try temporarily unloading the web site project until this fix is released.
